services:
  # 1. Base de Dados
  mysql-db:
    image: mysql:8.0
    container_name: gestaoativos_mysql
    restart: always
    environment:
      # Variáveis usadas pelo container MySQL para criar a BD
      MYSQL_ROOT_PASSWORD: root_password_segura 
      MYSQL_DATABASE: gestao_ativos_db        
      MYSQL_USER: user_gestao                  
      MYSQL_PASSWORD: user_password_segura     
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser_gestao", "-puser_password_segura"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Backend Auth (Login)
  auth-service:
    build:
      context: ./backend_auth
    container_name: gestaoativos_auth
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - ./backend_auth:/usr/src/app
      - /usr/src/app/node_modules
      - ./.env:/usr/src/app/.env  # MAPEIA O .ENV DA RAIZ PARA O CÓDIGO LER
    depends_on:
      mysql-db:
        condition: service_healthy 

  # 3. Backend App 
  app-service:
    build:
      context: ./backend_app
    container_name: gestaoativos_app
    restart: always
    env_file: .env
    ports:
      - "3002:3002"
    volumes:
      - ./backend_app:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend_app/uploads:/usr/src/app/uploads
      - ./.env:/usr/src/app/.env  # MAPEIA O .ENV DA RAIZ PARA O CÓDIGO LER
    depends_on:
      mysql-db:
        condition: service_healthy 

  # 4. Frontend (React/Vite)
  frontend:
    build:
      context: ./gestaoativos
    container_name: gestaoativos_frontend
    ports:
      - "3000:80"
    volumes:
      - ./gestaoativos:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      auth-service:
        condition: service_started
      app-service:
        condition: service_started

volumes:
  mysql_data: